// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-recent-leads.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_leads_default = defineTool({
  name: "list_recent_leads",
  title: "List recent leads",
  description: "List the most recent leads captured by the site (admin only). Returns name, email, source, stage, lead_score, and created_at.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("How many leads to return (default 10, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("leads").select("id, name, email, phone, source, stage, lead_score, lead_priority, created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/lead-stats.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.91.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var lead_stats_default = defineTool2({
  name: "lead_stats",
  title: "Lead stats",
  description: "Return counts of leads grouped by stage and by priority (admin only).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("leads").select("stage, lead_priority");
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    const byStage = {};
    const byPriority = {};
    for (const row of data ?? []) {
      const stage = row.stage ?? "unknown";
      const priority = row.lead_priority ?? "unknown";
      byStage[stage] = (byStage[stage] ?? 0) + 1;
      byPriority[priority] = (byPriority[priority] ?? 0) + 1;
    }
    const summary = { total: data?.length ?? 0, by_stage: byStage, by_priority: byPriority };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ibfjiqbdjqyzbcoaoltz";
var mcp_default = defineMcp({
  name: "freelance-digital-consultant-mcp",
  title: "Freelance Digital Consultant",
  version: "0.1.0",
  instructions: "Tools for the Freelance Digital Consultant CRM. Use `list_recent_leads` to fetch the latest leads captured by the site and `lead_stats` for a rollup of lead counts by stage and priority. All tools require an admin-authenticated user (RLS enforced).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_recent_leads_default, lead_stats_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
